### PR TITLE
Add snippets support

### PR DESCRIPTION
**Pull request by Leonx254**
Incorporate snippets support for v3 & v4 scripts

### CODE REVIEW

**Comment by Xeeynamo** [comment]
Hey @Leonx254 thanks for your PR. Is `event` instead of `sub` for v4? Do you have any code example I can see to verify the intent of this code change?

**Comment by Leonx254** [comment]
Thanks for the response, event is in fact the right term, discovered thanks to origins including the script compiler for v4, we had to do a soft-rework to the scripts to allow origins to run s1/s2 scripts.
You can find more examples in the script decomp github, on the cleanup branch, but i'll left one here for a quick check.

[Invincibility.txt](https://github.com/Xeeynamo/vscode-rsdk/files/9650025/Invincibility.txt)

**Comment by Xeeynamo** [comment]
Oh, I was not aware of the script decompiler rework. Let me know as soon as you do not intend to make any further change to the PR, so I can merge it and push the new version on the VSCode Marketplace :)

**Comment by Leonx254** [comment]
i have a friend doing a checkup because i got some things wrong from the outdated handbook, i'll let you know once i get his PR.
Thanks for your time!

**Comment by Leonx254** [comment]
Sorry for taking so long, we've been busy finishing up the cleanup for public testing.
My friend couldn't get time to make the PR, but instead pointed me most of the errors i got so i could fix it myself.
I don't expect to do more updates for now, so this is ready for merge

**Comment by Leonx254** [comment]
@Xeeynamo I'm sorry, i was supposed to mention you directly? i'm not really used to doing PR's

**Comment by Xeeynamo** [comment]
Pardon, I did not read this at all. Merging.

**Pull request merged**
